<a href="https://colab.research.google.com/github/Fairly-fire/Hamoye-Submissions/blob/main/DataStoryTellingStageE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# 2019-15

In [56]:
url1 = "https://investors.coca-colacompany.com/filings-reports/all-sec-filings/content/0000021344-20-000006/a2019123110-k.htm"

In [57]:
dataset1 = pd.read_html(url1)

In [58]:
dataset1

[     0   1                                                  2
 0  NaN NaN                                                NaN
 1  NaN NaN                                                NaN
 2    ☒ NaN  ANNUAL REPORT PURSUANT TO SECTION 13 OR 15(d) ...,
      0   1                                                  2
 0  NaN NaN                                                NaN
 1  NaN NaN                                                NaN
 2    ☐ NaN  TRANSITION REPORT PURSUANT TO SECTION 13 OR 15...,
                                                 0  \
 0                                             NaN
 1                                             NaN
 2                                        Delaware
 3  (State or other jurisdiction of incorporation)
 4                             One Coca-Cola Plaza
 5                                        Atlanta,
 6        (Address of principal executive offices)

                                                 1  \
 0                                             NaN
 1                                             NaN
 2                                        Delaware
 3  (State or other jurisdiction of incorporation)
 4                             One Coca-Cola Plaza
 5                                         Georgia
 6        (Address of principal executive offices)

                                       2
 0                                   NaN
 1                                   NaN
 2                            58-0628465
 3  (I.R.S. Employer Identification No.)
 4                                   NaN
 5                                 30313
 6                            (Zip Code)  ,
                                 0                  1  \
 0                             NaN                NaN
 1                             NaN                NaN
 2             Title of each class  Trading Symbol(s)
 3   Common Stock, $0.25 Par Value                 KO
 4           0.000% Notes Due 2021              KO21B
 5    Floating Rate Notes Due 2021              KO21C
 6           1.125% Notes Due 2022               KO22
 7           0.125% Notes Due 2022              KO22B
 8            0.75% Notes Due 2023              KO23B
 9           0.500% Notes Due 2024               KO24
 10          1.875% Notes Due 2026               KO26
 11          0.750% Notes Due 2026              KO26C
 12          1.125% Notes Due 2027               KO27
 13          1.250% Notes Due 2031               KO31
 14          1.625% Notes Due 2035               KO35
 15          1.100% Notes Due 2036               KO36

                                             2
 0                                         NaN
 1                                         NaN
 2   Name of each exchange on which registered
 3                     New York Stock Exchange
 4                     New York Stock Exchange
 5                     New York Stock Exchange
 6                     New York Stock Exchange
 7                     New York Stock Exchange
 8                     New York Stock Exchange
 9                     New York Stock Exchange
 10                    New York Stock Exchange
 11                    New York Stock Exchange
 12                    New York Stock Exchange
 13                    New York Stock Exchange
 14                    New York Stock Exchange
 15                    New York Stock Exchange  ,
                          0    1                  2    3  \
 0                      NaN  NaN                NaN  NaN
 1                      NaN  NaN                NaN  NaN
 2  Large accelerated filer    ☒  Accelerated filer    ☐

                        4    5                          6    7  \
 0                    NaN  NaN                        NaN  NaN
 1                    NaN  NaN                        NaN  NaN
 2  Non-accelerated filer    ☐  Smaller reporting company    ☐

                          8    9
 0                      NaN  NaN
 1                      NaN  NaN
 2  Emerging growth company    ☐  ,
            0                                                  1     2
 0        NaN                                                NaN   NaN
 1        NaN                                                NaN   NaN
 2        NaN                                                NaN  Page
 3        NaN                         Forward-Looking Statements     4
 4     Part I                                                NaN   NaN
 5    Item 1.                                           Business     4
 6   Item 1A.                                       Risk Factors    12
 7   Item 1B.                          Unresolved Staff Comments    24
 8    Item 2.                                         Properties    24
 9    Item 3.                                  Legal Proceedings    24
 10   Item 4.                            Mine Safety Disclosures    26
 11   Item X.           Information About Our Executive Officers    27
 12   Part II                                                NaN   NaN
 13   Item 5.  Market for Registrant's Common Equity, Related...    29
 14   Item 6.                            Selected Financial Data    31
 15   Item 7.  Management's Discussion and Analysis of Financ...    31
 16  Item 7A.  Quantitative and Qualitative Disclosures About...    65
 17   Item 8.        Financial Statements and Supplementary Data    67
 18   Item 9.  Changes in and Disagreements with Accountants ...   147
 19  Item 9A.                            Controls and Procedures   147
 20  Item 9B.                                  Other Information   147
 21  Part III                                                NaN   NaN
 22  Item 10.  Directors, Executive Officers and Corporate Go...   147
 23  Item 11.                             Executive Compensation   147
 24  Item 12.  Security Ownership of Certain Beneficial Owner...   147
 25  Item 13.  Certain Relationships and Related Transactions...   147
 26  Item 14.             Principal Accountant Fees and Services   148
 27   Part IV                                                NaN   NaN
 28  Item 15.         Exhibits and Financial Statement Schedules   148
 29  Item 16.                                  Form 10-K Summary   156
 30       NaN                                         Signatures   157,
      0                               1
 0  NaN                             NaN
 1    •  Europe, Middle East and Africa,
      0              1
 0  NaN            NaN
 1    •  Latin America,
      0              1
 0  NaN            NaN
 1    •  North America,
      0             1
 0  NaN           NaN
 1    •  Asia Pacific,
      0                1
 0  NaN              NaN
 1    •  Global Ventures,
      0                     1
 0  NaN                   NaN
 1    •  Bottling Investments,
      0                                                  1
 0  NaN                                                NaN
 1    •  "concentrates" means flavorings and other ingr...,
      0                                                  1
 0  NaN                                                NaN
 1    •  "syrups" means an intermediate product in the ...,
      0                                                  1
 0  NaN                                                NaN
 1    •  "fountain syrups" means syrups that are sold t...,
      0                                                  1
 0  NaN                                                NaN
 1    •  "Company Trademark Beverages" means beverages ...,
      0                                                  1
 0  NaN                                                NaN
 1    •  "Trademark Coca-Cola Beverages" or "Trademark ...,
      0                                                  1
 0  NaN                                                NaN
 1    •  beverage concentrates, sometimes referred to a...,
      0                                                  1
 0  NaN                                                NaN
 1    •  finished sparkling soft drinks and other nonal...,
      0                                                  1
 0  NaN                                                NaN
 1    •  sparkling soft drinks: Coca-Cola, Diet Coke/Co...,
      0                                                  1
 0  NaN                                                NaN
 1    •  water, enhanced water and sports drinks: Aquar...,
      0                                                  1
 0  NaN                                                NaN
 1    •  juice, dairy and plant-based beverages: AdeS, ...,
      0                                                  1
 0  NaN                                                NaN
 1    •  tea and coffee: Ayataka, Costa, doğadan, FUZE ...,
      0                                                  1
 0  NaN                                                NaN
 1    •  Certain Coca-Cola system bottlers distribute c...,
      0                                                  1
 0  NaN                                                NaN
 1    •  We have a strategic partnership with Aujan Ind...,
      0                                                  1
 0  NaN                                                NaN
 1    •  Coca-Cola FEMSA, S.A.B. de C.V. ("Coca-Cola FE...,
      0                                                  1
 0  NaN                                                NaN
 1    •  Coca-Cola European Partners plc ("CCEP"), whic...,
      0                                                  1
 0  NaN                                                NaN
 1    •  Coca-Cola HBC AG ("Coca-Cola Hellenic"), which...,
      0                                                  1
 0  NaN                                                NaN
 1    •  Arca Continental, S.A.B. de C.V., which has bo...,
      0                                                  1
 0  NaN                                                NaN
 1    •  Swire Beverages, which has bottling and distri...,
      0                                                  1
 0  NaN                                                NaN
 1    •  below a "safe harbor" threshold that may be es...,
      0                     1
 0  NaN                   NaN
 1    •  naturally occurring;,
      0                                    1
 0  NaN                                  NaN
 1    •  the result of necessary cooking; or,
      0                                         1
 0  NaN                                       NaN
 1    •  subject to another applicable exemption.,
                               0                                          1   \
 0                            NaN                                        NaN
 1                            NaN                                        NaN
 2                            NaN  Principal Concentrate and/or Syrup Plants
 3                            NaN                                      Owned
 4   Europe, Middle East & Africa                                          6
 5                  Latin America                                          5
 6                  North America                                         11
 7                   Asia Pacific                                          6
 8                Global Ventures                                          1
 9           Bottling Investments                                          —
 10                     Corporate                                          3
 11                         Total                                         32

                                            2   \
 0                                         NaN
 1                                         NaN
 2   Principal Concentrate and/or Syrup Plants
 3                                         NaN
 4                                         NaN
 5                                         NaN
 6                                         NaN
 7                                         NaN
 8                                         NaN
 9                                         NaN
 10                                        NaN
 11                                        NaN

                                            3   \
 0                                         NaN
 1                                         NaN
 2   Principal Concentrate and/or Syrup Plants
 3                                         NaN
 4                                         NaN
 5                                         NaN
 6                                         NaN
 7                                         NaN
 8                                         NaN
 9                                         NaN
 10                                        NaN
 11                                        NaN

                                            4   \
 0                                         NaN
 1                                         NaN
 2   Principal Concentrate and/or Syrup Plants
 3                                      Leased
 4                                           —
 5                                           —
 6                                           —
 7                                           —
 8                                           —
 9                                           —
 10                                          —
 11                                          —

                                            5   6   \
 0                                         NaN NaN
 1                                         NaN NaN
 2   Principal Concentrate and/or Syrup Plants NaN
 3                                         NaN NaN
 4                                         NaN NaN
 5                                         NaN NaN
 6                                         NaN NaN
 7                                         NaN NaN
 8                                         NaN NaN
 9                                         NaN NaN
 10                                        NaN NaN
 11                                        NaN NaN

                                                   7   \
 0                                                NaN
 1                                                NaN
 2   Principal Beverage Manufacturing/Bottling Plants
 3                                              Owned
 4                                                  —
 5                                                  —
 6                                                  9
 7                                                  —
 8                                                  1
 9                                                 87
 10                                                 —
 11                                                97

                                                   8   \
 0                                                NaN
 1                                                NaN
 2   Principal Beverage Manufacturing/Bottling Plants
 3                                                NaN
 4                                                NaN
 5                                                NaN
 6                                                NaN
 7                                                NaN
 8                                                NaN
 9                                                NaN
 10                                               NaN
 11                                               NaN

                                                   9   ...  \
 0                                                NaN  ...
 1                                                NaN  ...
 2   Principal Beverage Manufacturing/Bottling Plants  ...
 3                                                NaN  ...
 4                                                NaN  ...
 5                                                NaN  ...
 6                                                NaN  ...
 7                                                NaN  ...
 8                                                NaN  ...
 9                                                NaN  ...
 10                                               NaN  ...
 11                                               NaN  ...

                                                14  \
 0                                             NaN
 1                                             NaN
 2   Principal Distribution and Storage Warehouses
 3                                             NaN
 4                                             NaN
 5                                             NaN
 6                                             NaN
 7                                             NaN
 8                                             NaN
 9                                             NaN
 10                                            NaN
 11                                            NaN

                                                15  \
 0                                             NaN
 1                                             NaN
 2   Principal Distribution and Storage Warehouses
 3                                             NaN
 4                                             NaN
 5                                             NaN
 6                                             NaN
 7                                             NaN
 8                                             NaN
 9                                             NaN
 10                                            NaN
 11                                            NaN

                                                16  \
 0                                             NaN
 1                                             NaN
 2   Principal Distribution and Storage Warehouses
 3                                          Leased
 4                                              25
 5                                               3
 6                                              38
 7                                               —
 8                                               1
 9                                              97
 10                                              7
 11                                            171

                                                17  18  \
 0                                             NaN NaN
 1                                             NaN NaN
 2   Principal Distribution and Storage Warehouses NaN
 3                                             NaN NaN
 4                                             NaN NaN
 5                                             NaN NaN
 6                                             NaN NaN
 7                                             NaN NaN
 8                                             NaN NaN
 9                                             NaN NaN
 10                                            NaN NaN
 11                                            NaN NaN

                          19                       20                       21  \
 0                       NaN                      NaN                      NaN
 1                       NaN                      NaN                      NaN
 2   Principal Retail Stores  Principal Retail Stores  Principal Retail Stores
 3                     Owned                      NaN                      NaN
 4                         —                      NaN                      NaN
 5                         —                      NaN                      NaN
 6                         —                      NaN                      NaN
 7                         —                      NaN                      NaN
 8                         —                      NaN                      NaN
 9                         —                      NaN                      NaN
 10                        —                      NaN                      NaN
 11                        —                      NaN                      NaN


In [59]:
len(dataset1)

426

In [60]:
#using index to get your table

financial_report19 = dataset1[40]

In [61]:
financial_report19.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Year Ended December 31,",2019,2019.00,NaN,2018,2018.00,NaN,2017,2017.00,NaN,2016,2016.00,NaN,2015,2015.00,NaN
3,(In millions except per share data),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Summary of Operations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Net operating revenues,$,37266.00,NaN,$,34300.00,NaN,$,36212.00,NaN,$,41863.00,NaN,$,44294.00,NaN
6,Consolidated net income,8985,8985.00,NaN,6476,6476.00,NaN,1283,1283.00,NaN,6550,6550.00,NaN,7366,7366.00,NaN
7,Net income attributable to shareowners of The ...,8920,8920.00,NaN,6434,6434.00,NaN,1248,1248.00,NaN,6527,6527.00,NaN,7351,7351.00,NaN
8,Per Share Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Basic net income,$,2.09,NaN,$,1.51,NaN,$,0.29,NaN,$,1.51,NaN,$,1.69,NaN

In [62]:
#selecting the relevant columns
financial_report19 = dataset1[40][[0,2,5,8,11,14]]
financial_report19

,0,2,5,8,11,14
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,"Year Ended December 31,",2019.00,2018.00,2017.00,2016.00,2015.00
3,(In millions except per share data),NaN,NaN,NaN,NaN,NaN
4,Summary of Operations,NaN,NaN,NaN,NaN,NaN
5,Net operating revenues,37266.00,34300.00,36212.00,41863.00,44294.00
6,Consolidated net income,8985.00,6476.00,1283.00,6550.00,7366.00
7,Net income attributable to shareowners of The ...,8920.00,6434.00,1248.00,6527.00,7351.00
8,Per Share Data,NaN,NaN,NaN,NaN,NaN
9,Basic net income,2.09,1.51,0.29,1.51,1.69
10,Diluted net income,2.07,1.50,0.29,1.49,1.67
11,Cash dividends,1.60,1.56,1.48,1.40,1.32
12,Balance Sheet Data,NaN,NaN,NaN,NaN,NaN
13,Total assets,86381.00,83216.00,87896.00,87270.00,89996.00
14,Long-term debt,27516.00,25376.00,31202.00,29684.00,28311.00

In [63]:
#removing null values
financial_report19 = financial_report19.dropna()
financial_report19

,0,2,5,8,11,14
2,"Year Ended December 31,",2019.00,2018.00,2017.00,2016.00,2015.00
5,Net operating revenues,37266.00,34300.00,36212.00,41863.00,44294.00
6,Consolidated net income,8985.00,6476.00,1283.00,6550.00,7366.00
7,Net income attributable to shareowners of The ...,8920.00,6434.00,1248.00,6527.00,7351.00
9,Basic net income,2.09,1.51,0.29,1.51,1.69
10,Diluted net income,2.07,1.50,0.29,1.49,1.67
11,Cash dividends,1.60,1.56,1.48,1.40,1.32
13,Total assets,86381.00,83216.00,87896.00,87270.00,89996.00
14,Long-term debt,27516.00,25376.00,31202.00,29684.00,28311.00

In [64]:
#naming all columns
financial_report19.columns = ['31 Dec End of Year', '2019',	'2018',	'2017',	'2016',	'2015']
financial_report19

,31 Dec End of Year,2019,2018,2017,2016,2015
2,"Year Ended December 31,",2019.00,2018.00,2017.00,2016.00,2015.00
5,Net operating revenues,37266.00,34300.00,36212.00,41863.00,44294.00
6,Consolidated net income,8985.00,6476.00,1283.00,6550.00,7366.00
7,Net income attributable to shareowners of The ...,8920.00,6434.00,1248.00,6527.00,7351.00
9,Basic net income,2.09,1.51,0.29,1.51,1.69
10,Diluted net income,2.07,1.50,0.29,1.49,1.67
11,Cash dividends,1.60,1.56,1.48,1.40,1.32
13,Total assets,86381.00,83216.00,87896.00,87270.00,89996.00
14,Long-term debt,27516.00,25376.00,31202.00,29684.00,28311.00

In [65]:
#remove unneccerassary rows
financial_report19 =  financial_report19.drop(financial_report19.index[0])

financial_report19

,31 Dec End of Year,2019,2018,2017,2016,2015
5,Net operating revenues,37266.00,34300.00,36212.00,41863.00,44294.00
6,Consolidated net income,8985.00,6476.00,1283.00,6550.00,7366.00
7,Net income attributable to shareowners of The ...,8920.00,6434.00,1248.00,6527.00,7351.00
9,Basic net income,2.09,1.51,0.29,1.51,1.69
10,Diluted net income,2.07,1.50,0.29,1.49,1.67
11,Cash dividends,1.60,1.56,1.48,1.40,1.32
13,Total assets,86381.00,83216.00,87896.00,87270.00,89996.00
14,Long-term debt,27516.00,25376.00,31202.00,29684.00,28311.00

In [66]:
#resetting the index
financial_report19.reset_index(inplace = True)
financial_report19

,index,31 Dec End of Year,2019,2018,2017,2016,2015
0,5,Net operating revenues,37266.00,34300.00,36212.00,41863.00,44294.00
1,6,Consolidated net income,8985.00,6476.00,1283.00,6550.00,7366.00
2,7,Net income attributable to shareowners of The ...,8920.00,6434.00,1248.00,6527.00,7351.00
3,9,Basic net income,2.09,1.51,0.29,1.51,1.69
4,10,Diluted net income,2.07,1.50,0.29,1.49,1.67
5,11,Cash dividends,1.60,1.56,1.48,1.40,1.32
6,13,Total assets,86381.00,83216.00,87896.00,87270.00,89996.00
7,14,Long-term debt,27516.00,25376.00,31202.00,29684.00,28311.00

In [67]:
#drop the index column
financial_report19.drop(columns=['index'], inplace = True)
financial_report19

,31 Dec End of Year,2019,2018,2017,2016,2015
0,Net operating revenues,37266.00,34300.00,36212.00,41863.00,44294.00
1,Consolidated net income,8985.00,6476.00,1283.00,6550.00,7366.00
2,Net income attributable to shareowners of The ...,8920.00,6434.00,1248.00,6527.00,7351.00
3,Basic net income,2.09,1.51,0.29,1.51,1.69
4,Diluted net income,2.07,1.50,0.29,1.49,1.67
5,Cash dividends,1.60,1.56,1.48,1.40,1.32
6,Total assets,86381.00,83216.00,87896.00,87270.00,89996.00
7,Long-term debt,27516.00,25376.00,31202.00,29684.00,28311.00

In [68]:
#check datatypes
financial_report19.dtypes

31 Dec End of Year     object
2019                  float64
2018                  float64
2017                  float64
2016                  float64
2015                  float64
dtype: object

In [70]:
#making a pie chart for year 2019
fig = px.pie(financial_report19, values='2019', names='31 Dec End of Year', title = '2019 Yearly financial report')
fig.show()

In [71]:
#making a pie chart for year 2018
fig = px.pie(financial_report19, values='2018', names='31 Dec End of Year', title = '2018 Yearly financial report')
fig.show()

In [72]:
#making a pie chart for year 2017
fig = px.pie(financial_report19, values='2017', names='31 Dec End of Year', title = '2017 Yearly financial report')
fig.show()

In [73]:
#making a pie chart for year 2016
fig = px.pie(financial_report19, values='2016', names='31 Dec End of Year', title = '2016 Yearly financial report')
fig.show()

In [74]:
#making a pie chart for year 2015
fig = px.pie(financial_report19, values='2015', names='31 Dec End of Year', title = '2015 Yearly financial report')
fig.show()

# 2014-10

In [75]:
url2 = "https://investors.coca-colacompany.com/filings-reports/all-sec-filings/content/0000021344-15-000005/a2014123110-k.htm"

In [76]:
dataset2 = pd.read_html(url2)

In [77]:
dataset2

[     0   1                                                  2
 0  NaN NaN                                                NaN
 1  NaN NaN                                                NaN
 2    ý NaN  ANNUAL REPORT PURSUANT TO SECTION 13 OR 15(d) ...,
      0   1                                                  2
 0  NaN NaN                                                NaN
 1  NaN NaN                                                NaN
 2    o NaN  TRANSITION REPORT PURSUANT TO SECTION 13 OR 15...,
                                                    0   1  \
 0                                                NaN NaN
 1                                                NaN NaN
 2  DELAWARE(State or other jurisdiction of incorp... NaN
 3  One Coca-Cola PlazaAtlanta, Georgia(Address of... NaN

                                              2
 0                                          NaN
 1                                          NaN
 2  58-0628465(IRS Employer Identification No.)
 3                              30313(Zip Code)  ,
                                0   1  \
 0                            NaN NaN
 1                            NaN NaN
 2            Title of each class NaN
 3  COMMON STOCK, $0.25 PAR VALUE NaN

                                            2
 0                                        NaN
 1                                        NaN
 2  Name of each exchange on which registered
 3                    NEW YORK STOCK EXCHANGE  ,
                                                0  \
 0                                            NaN
 1                                            NaN
 2                      Large accelerated filer ý
 3  (Do not check if a smaller reporting company)

                                                1  \
 0                                            NaN
 1                                            NaN
 2                                            NaN
 3  (Do not check if a smaller reporting company)

                                                2  \
 0                                            NaN
 1                                            NaN
 2                            Accelerated filer o
 3  (Do not check if a smaller reporting company)

                                                3  \
 0                                            NaN
 1                                            NaN
 2                                            NaN
 3  (Do not check if a smaller reporting company)

                                                4  \
 0                                            NaN
 1                                            NaN
 2                        Non-accelerated filer o
 3  (Do not check if a smaller reporting company)

                                                5  \
 0                                            NaN
 1                                            NaN
 2                                            NaN
 3  (Do not check if a smaller reporting company)

                                                6
 0                                            NaN
 1                                            NaN
 2                    Smaller reporting company o
 3  (Do not check if a smaller reporting company)  ,
            0                                                  1     2
 0        NaN                                                NaN   NaN
 1        NaN                                                NaN   NaN
 2        NaN                                                NaN  Page
 3        NaN                         Forward-Looking Statements     1
 4     Part I                                                NaN   NaN
 5    Item 1.                                           Business     1
 6   Item 1A.                                       Risk Factors    12
 7   Item 1B.                          Unresolved Staff Comments    21
 8    Item 2.                                         Properties    21
 9    Item 3.                                  Legal Proceedings    22
 10   Item 4.                            Mine Safety Disclosures    23
 11   Item X.                  Executive Officers of the Company    23
 12   Part II                                                NaN   NaN
 13   Item 5.  Market for Registrant's Common Equity, Related...    26
 14   Item 6.                            Selected Financial Data    29
 15   Item 7.  Management's Discussion and Analysis of Financ...    29
 16  Item 7A.  Quantitative and Qualitative Disclosures About...    70
 17   Item 8.        Financial Statements and Supplementary Data    72
 18   Item 9.  Changes in and Disagreements with Accountants ...   142
 19  Item 9A.                            Controls and Procedures   142
 20  Item 9B.                                  Other Information   142
 21  Part III                                                NaN   NaN
 22  Item 10.  Directors, Executive Officers and Corporate Go...   142
 23  Item 11.                             Executive Compensation   142
 24  Item 12.  Security Ownership of Certain Beneficial Owner...   142
 25  Item 13.  Certain Relationships and Related Transactions...   143
 26  Item 14.             Principal Accountant Fees and Services   143
 27   Part IV                                                NaN   NaN
 28  Item 15.         Exhibits and Financial Statement Schedules   143
 29       NaN                                         Signatures   152,
      0                   1
 0  NaN                 NaN
 1    •  Eurasia and Africa,
      0       1
 0  NaN     NaN
 1    •  Europe,
      0              1
 0  NaN            NaN
 1    •  Latin America,
      0              1
 0  NaN            NaN
 1    •  North America,
      0             1
 0  NaN           NaN
 1    •  Asia Pacific,
      0                     1
 0  NaN                   NaN
 1    •  Bottling Investments,
      0          1
 0  NaN        NaN
 1    •  Corporate,
      0                                                  1
 0  NaN                                                NaN
 1    •  "concentrates" means flavoring ingredients and...,
      0                                                  1
 0  NaN                                                NaN
 1    •  "syrups" means beverage ingredients produced b...,
      0                                                  1
 0  NaN                                                NaN
 1    •  "fountain syrups" means syrups that are sold t...,
      0                                                  1
 0  NaN                                                NaN
 1    •  "sparkling beverages" means nonalcoholic ready...,
      0                                                  1
 0  NaN                                                NaN
 1    •  "still beverages" means nonalcoholic beverages...,
      0                                                  1
 0  NaN                                                NaN
 1    •  "Company Trademark Beverages" means beverages ...,
      0                                                  1
 0  NaN                                                NaN
 1    •  "Trademark Coca-Cola Beverages" or "Trademark ...,
      0                                                  1
 0  NaN                                                NaN
 1    •  beverage concentrates, sometimes referred to a...,
      0                                                  1
 0  NaN                                                NaN
 1    •  finished sparkling and still beverages (we ref...,
                            0            1                     2  \
 0                        NaN          NaN                   NaN
 1                        NaN          NaN                   NaN
 2                  Coca-Cola  Minute Maid              Aquarius
 3  Diet Coke/Coca-Cola Light     Georgia1     Minute Maid Pulpy
 4             Coca-Cola Zero     Powerade                Dasani
 5                      Fanta   Del Valle2               Simply4
 6                     Sprite   Schweppes3  Glacéau Vitaminwater

                 3
 0             NaN
 1             NaN
 2  Bonaqua/Bonaqa
 3        Ayataka5
 4      Gold Peak6
 5        I LOHAS7
 6       FUZE TEA8  ,
      0                                                  1
 0  NaN                                                NaN
 1  1.0  Georgia is primarily a coffee brand sold mainl...,
      0                                                  1
 0  NaN                                                NaN
 1  2.0  We manufacture, market and sell juices and jui...,
      0                                                  1
 0  NaN                                                NaN
 1  3.0  Schweppes is owned by the Company in certain c...,
      0                                                  1
 0  NaN                                                NaN
 1  4.0  Simply is a juice and juice drink brand sold i...,
      0                                            1
 0  NaN                                          NaN
 1  5.0  Ayataka is a green tea brand sold in Japan.,
      0                                                  1
 0  NaN                                                NaN
 1  6.0  Gold Peak is primarily a tea brand sold in Nor...,
      0                                        1
 0  NaN                                      NaN
 1  7.0  I LOHAS is a water brand sold in Japan.,
      0                                                  1
 0  NaN                                                NaN
 1  8.0  FUZE TEA is a brand sold outside of North Amer...,
      0                                                  1
 0  NaN                                                NaN
 1    •  We produce and/or distribute certain other thi...,
      0                                                  1
 0  NaN                                                NaN
 1    •  We have a joint venture with Nestlé S.A. ("Nes...,
      0                                                  1
 0  NaN                                                NaN
 1    •  We have a strategic partnership with Aujan Ind...,
      0                                                  1
 0  NaN                                                NaN
 1    •  We distribute certain brands of Monster Bevera...,
      0                                                  1
 0  NaN                                                NaN
 1    •  Coca-Cola FEMSA, S.A.B. de C.V. (“Coca-Cola FE...,
      0                                                  1
 0  NaN                                                NaN
 1    •  Coca-Cola HBC AG (“Coca-Cola Hellenic”), which...,
      0                                                  1
 0  NaN                                                NaN
 1    •  Arca Continental, S.A.B. de C.V., which has bo...,
      0                                                  1
 0  NaN                                                NaN
 1    •  New CCE, which has bottling and distribution o...,
      0                                                  1
 0  NaN                                                NaN
 1    •  Swire Beverages (“Swire”), which has bottling ...,
      0                                                  1
 0  NaN                                                NaN
 1    •  below a "safe harbor" threshold that may be es...,
      0                     1
 0  NaN                   NaN
 1    •  naturally occurring;,
      0                                    1
 0  NaN                                  NaN
 1    •  the result of necessary cooking; or,
      0                                         1
 0  NaN                                       NaN
 1    •  subject to another applicable exemption.,
                 0                          1                          2   \
 0              NaN                        NaN                        NaN
 1              NaN                        NaN                        NaN
 2              NaN  Common StockMarket Prices  Common StockMarket Prices
 3              NaN                       High                       High
 4             2014                        NaN                        NaN
 5   Fourth quarter                          $                      45.00
 6    Third quarter                      42.57                      42.57
 7   Second quarter                      42.29                      42.29
 8    First quarter                      41.23                      41.23
 9             2013                        NaN                        NaN
 10  Fourth quarter                          $                      41.39
 11   Third quarter                      41.25                      41.25
 12  Second quarter                      43.43                      43.43
 13   First quarter                      40.70                      40.70

                            3                          4   \
 0                         NaN                        NaN
 1                         NaN                        NaN
 2   Common StockMarket Prices  Common StockMarket Prices
 3                         NaN                        NaN
 4                         NaN                        NaN
 5                         NaN                        NaN
 6                         NaN                        NaN
 7                         NaN                        NaN
 8                         NaN                        NaN
 9                         NaN                        NaN
 10                        NaN                        NaN
 11                        NaN                        NaN
 12                        NaN                        NaN
 13                        NaN                        NaN

                            5                          6   \
 0                         NaN                        NaN
 1                         NaN                        NaN
 2   Common StockMarket Prices  Common StockMarket Prices
 3                         Low                        Low
 4                         NaN                        NaN
 5                           $                      39.80
 6                       39.06                      39.06
 7                       38.04                      38.04
 8                       36.89                      36.89
 9                         NaN                        NaN
 10                          $                      36.83
 11                      37.80                      37.80
 12                      38.97                      38.97
 13                      36.52                      36.52

                            7   8                  9                  10  11
 0                         NaN NaN                NaN                NaN NaN
 1                         NaN NaN                NaN                NaN NaN
 2   Common StockMarket Prices NaN                NaN                NaN NaN
 3                         NaN NaN  DividendsDeclared  DividendsDeclared NaN
 4                         NaN NaN                NaN                NaN NaN
 5                         NaN NaN                  $              0.305 NaN
 6                         NaN NaN              0.305              0.305 NaN
 7                         NaN NaN              0.305              0.305 NaN
 8                         NaN NaN              0.305              0.305 NaN
 9                         NaN NaN                NaN                NaN NaN
 10                        NaN NaN                  $              0.280 NaN
 11                        NaN NaN              0.280              0.280 NaN
 12                        NaN NaN              0.280              0.280 NaN
 13                        NaN NaN              0.280              0.280 NaN  ,
                                             0   \
 0                                          NaN
 1                                          NaN
 2                                       Period
 3  September 27, 2014 through October 24, 2014
 4   October 25, 2014 through November 21, 2014
 5  November 22, 2014 through December 31, 2014
 6                                        Total

                                  1   2   3                           4   \
 0                               NaN NaN NaN                         NaN
 1                               NaN NaN NaN                         NaN
 2  Total Number ofShares Purchased1 NaN NaN  AveragePrice PaidPer Share
 3                           5150833 NaN NaN                           $
 4                           9997513 NaN NaN                       42.25
 5                          11721766 NaN NaN                       42.77
 6                          26870112 NaN NaN                           $

                            5   6   7   \
 0                         NaN NaN NaN
 1                         NaN NaN NaN
 2  AveragePrice PaidPer Share NaN NaN
 3                       42.03 NaN NaN
 4                       42.25 NaN NaN
 5                       42.77 NaN NaN
 6                       42.43 NaN NaN

                                                   8   9   10  \
 0                                                NaN NaN NaN
 1                                                NaN NaN NaN
 2  Total Number ofShares Purchasedas Part of Publ... NaN NaN
 3                                            5150833 NaN NaN
 4                                            9967698 NaN NaN
 5                                           11707800 NaN NaN
 6                                           26826331 NaN NaN

                                                   11  12
 0                                                NaN NaN
 1                                                NaN NaN
 2  Maximum Number ofShares That MayYet Be Purchas... NaN
 3                                          345200820 NaN
 4                                          335233122 NaN
 5                                          323525322 NaN
 6                                                NaN NaN  ,
      0                                                  1
 0  NaN                                                NaN
 1  1.0  The total number of shares purchased includes:...,
      0                                                  1
 0  NaN                                                NaN
 1  2.0  On October 18, 2012, the Company publicly anno...,
                       0     1       2   3     4       5   6     7       8   \
 0                    NaN   NaN     NaN NaN   NaN     NaN NaN   NaN     NaN
 1                    NaN   NaN     NaN NaN   NaN     NaN NaN   NaN     NaN
 2           December 31,  2009  2009.0 NaN  2010  2010.0 NaN  2011  2011.0
 3  The Coca-Cola Company     $   100.0 NaN     $   119.0 NaN     $   130.0
 4       Peer Group Index   100   100.0 NaN   119   119.0 NaN   142   142.0
 5          S&P 500 Index   100   100.0 NaN   115   115.0 NaN   117   117.0

    9     10      11  12    13      14  15    16      17  18
 0 NaN   NaN     NaN NaN   NaN     NaN NaN   NaN     NaN NaN
 1 NaN   NaN     NaN NaN   NaN     NaN NaN   NaN     NaN NaN
 2 NaN  2012  2012.0 NaN  2013  2013.0 NaN  2014  2014.0 NaN
 3 NaN     $   139.0 NaN     $   163.0 NaN     $   171.0 NaN
 4 NaN   156   156.0 NaN   198   198.0 NaN   229   229.0 NaN
 5 NaN   136   136.0 NaN   180   180.0 NaN   205   205.0 NaN  ,
                                                    0      1         2   3   \
 0                                                 NaN    NaN       NaN NaN
 1                                                 NaN    NaN       NaN NaN
 2                             Year Ended December 31,   2014   2014.00 NaN
 3                 (In millions except per share data)    NaN       NaN NaN
 4                               SUMMARY OF OPERATIONS    NaN       NaN NaN
 5                              Net operating revenues      $  45998.00 NaN
 6   Net income attributable to shareowners of The ...   7098   7098.00 NaN

In [78]:
len(dataset2)

434

In [90]:
#using index to get your table

financial_report14 = dataset2[49]

In [91]:
financial_report14.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Year Ended December 31,",2014,2014.00,NaN,NaN,2013 1,2013 1,NaN,NaN,2012,2012.00,NaN,NaN,2011,2011.00,NaN,NaN,2010 2,2010 2,NaN
3,(In millions except per share data),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SUMMARY OF OPERATIONS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Net operating revenues,$,45998.00,NaN,NaN,$,46854,NaN,NaN,$,48017.00,NaN,NaN,$,46542.00,NaN,NaN,$,35119,NaN
6,Net income attributable to shareowners of The ...,7098,7098.00,NaN,NaN,8584,8584,NaN,NaN,9019,9019.00,NaN,NaN,8584,8584.00,NaN,NaN,11787,11787,NaN
7,PER SHARE DATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Basic net income,$,1.62,NaN,NaN,$,1.94,NaN,NaN,$,2.00,NaN,NaN,$,1.88,NaN,NaN,$,2.55,NaN
9,Diluted net income,1.60,1.60,NaN,NaN,1.90,1.90,NaN,NaN,1.97,1.97,NaN,NaN,1.85,1.85,NaN,NaN,2.53,2.53,NaN

In [93]:
#selecting the relevant columns
financial_report14 = dataset2[49][[0,2,6,10,14,18]]
financial_report14

,0,2,6,10,14,18
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,"Year Ended December 31,",2014.00,2013 1,2012.00,2011.00,2010 2
3,(In millions except per share data),NaN,NaN,NaN,NaN,NaN
4,SUMMARY OF OPERATIONS,NaN,NaN,NaN,NaN,NaN
5,Net operating revenues,45998.00,46854,48017.00,46542.00,35119
6,Net income attributable to shareowners of The ...,7098.00,8584,9019.00,8584.00,11787
7,PER SHARE DATA,NaN,NaN,NaN,NaN,NaN
8,Basic net income,1.62,1.94,2.00,1.88,2.55
9,Diluted net income,1.60,1.90,1.97,1.85,2.53
10,Cash dividends,1.22,1.12,1.02,0.94,0.88
11,BALANCE SHEET DATA,NaN,NaN,NaN,NaN,NaN
12,Total assets,92023.00,90055,86174.00,79974.00,72921
13,Long-term debt,19063.00,19154,14736.00,13656.00,14041

In [94]:
#removing null values
financial_report14 = financial_report14.dropna()
financial_report14

,0,2,6,10,14,18
2,"Year Ended December 31,",2014.00,2013 1,2012.00,2011.00,2010 2
5,Net operating revenues,45998.00,46854,48017.00,46542.00,35119
6,Net income attributable to shareowners of The ...,7098.00,8584,9019.00,8584.00,11787
8,Basic net income,1.62,1.94,2.00,1.88,2.55
9,Diluted net income,1.60,1.90,1.97,1.85,2.53
10,Cash dividends,1.22,1.12,1.02,0.94,0.88
12,Total assets,92023.00,90055,86174.00,79974.00,72921
13,Long-term debt,19063.00,19154,14736.00,13656.00,14041

In [95]:
#naming all columns
financial_report14.columns = ['31 Dec End of Year', '2014',	'2013',	'2012',	'2011',	'2010']
financial_report14

,31 Dec End of Year,2014,2013,2012,2011,2010
2,"Year Ended December 31,",2014.00,2013 1,2012.00,2011.00,2010 2
5,Net operating revenues,45998.00,46854,48017.00,46542.00,35119
6,Net income attributable to shareowners of The ...,7098.00,8584,9019.00,8584.00,11787
8,Basic net income,1.62,1.94,2.00,1.88,2.55
9,Diluted net income,1.60,1.90,1.97,1.85,2.53
10,Cash dividends,1.22,1.12,1.02,0.94,0.88
12,Total assets,92023.00,90055,86174.00,79974.00,72921
13,Long-term debt,19063.00,19154,14736.00,13656.00,14041

In [96]:
#remove unneccerassary rows
financial_report14 =  financial_report14.drop(financial_report14.index[0])

financial_report14

,31 Dec End of Year,2014,2013,2012,2011,2010
5,Net operating revenues,45998.00,46854,48017.00,46542.00,35119
6,Net income attributable to shareowners of The ...,7098.00,8584,9019.00,8584.00,11787
8,Basic net income,1.62,1.94,2.00,1.88,2.55
9,Diluted net income,1.60,1.90,1.97,1.85,2.53
10,Cash dividends,1.22,1.12,1.02,0.94,0.88
12,Total assets,92023.00,90055,86174.00,79974.00,72921
13,Long-term debt,19063.00,19154,14736.00,13656.00,14041

In [97]:
#resetting the index
financial_report14.reset_index(inplace = True)
financial_report14

,index,31 Dec End of Year,2014,2013,2012,2011,2010
0,5,Net operating revenues,45998.00,46854,48017.00,46542.00,35119
1,6,Net income attributable to shareowners of The ...,7098.00,8584,9019.00,8584.00,11787
2,8,Basic net income,1.62,1.94,2.00,1.88,2.55
3,9,Diluted net income,1.60,1.90,1.97,1.85,2.53
4,10,Cash dividends,1.22,1.12,1.02,0.94,0.88
5,12,Total assets,92023.00,90055,86174.00,79974.00,72921
6,13,Long-term debt,19063.00,19154,14736.00,13656.00,14041

In [98]:
#drop the index column
financial_report14.drop(columns=['index'], inplace = True)
financial_report14

,31 Dec End of Year,2014,2013,2012,2011,2010
0,Net operating revenues,45998.00,46854,48017.00,46542.00,35119
1,Net income attributable to shareowners of The ...,7098.00,8584,9019.00,8584.00,11787
2,Basic net income,1.62,1.94,2.00,1.88,2.55
3,Diluted net income,1.60,1.90,1.97,1.85,2.53
4,Cash dividends,1.22,1.12,1.02,0.94,0.88
5,Total assets,92023.00,90055,86174.00,79974.00,72921
6,Long-term debt,19063.00,19154,14736.00,13656.00,14041

In [100]:
#check datatypes
financial_report14.dtypes

31 Dec End of Year     object
2014                  float64
2013                   object
2012                  float64
2011                  float64
2010                   object
dtype: object

In [101]:
#convert object to float
financial_report14[['2014',	'2013',	'2012',	'2011',	'2010']] = financial_report14[['2014',	'2013',	'2012',	'2011',	'2010']].astype(float)

In [102]:
financial_report14.dtypes

31 Dec End of Year     object
2014                  float64
2013                  float64
2012                  float64
2011                  float64
2010                  float64
dtype: object

In [103]:
#making a pie chart for year 2014
fig = px.pie(financial_report14, values='2014', names='31 Dec End of Year', title = '2014 Yearly financial report')
fig.show()

In [104]:
#making a pie chart for year 2013
fig = px.pie(financial_report14, values='2013', names='31 Dec End of Year', title = '2013 Yearly financial report')
fig.show()

In [105]:
#making a pie chart for year 2012
fig = px.pie(financial_report14, values='2012', names='31 Dec End of Year', title = '2012 Yearly financial report')
fig.show()

In [106]:
#making a pie chart for year 2011
fig = px.pie(financial_report14, values='2011', names='31 Dec End of Year', title = '2011 Yearly financial report')
fig.show()

In [107]:
#making a pie chart for year 2010
fig = px.pie(financial_report14, values='2010', names='31 Dec End of Year', title = '2010 Yearly financial report')
fig.show()

# 2009

In [2]:
url = "https://investors.coca-colacompany.com/filings-reports/all-sec-filings/content/0001047469-10-001476/a2195739z10-k.htm#dm19701_item_6._selected_financial_data"

In [3]:
dataset = pd.read_html(url)

In [4]:
dataset

[                                             0  \
 0                                          NaN
 1                                            ý
 2  For the fiscal year ended December 31, 2009
 3                                           OR
 4                                            o
 5            For the transition period from to

                                              1  \
 0                                          NaN
 1                                          NaN
 2  For the fiscal year ended December 31, 2009
 3                                           OR
 4                                          NaN
 5            For the transition period from to

                                                    2
 0                                                NaN
 1  ANNUAL REPORT PURSUANT TO SECTION 13 OR 15(d) ...
 2        For the fiscal year ended December 31, 2009
 3                                                 OR
 4  TRANSITION REPORT PURSUANT TO SECTION 13 OR 15...
 5                  For the transition period from to  ,
                                                    0   1  \
 0                                                NaN NaN
 1  DELAWARE (State or other jurisdiction of incor... NaN
 2  One Coca-Cola Plaza Atlanta, Georgia (Address ... NaN

                                               2
 0                                           NaN
 1  58-0628465 (IRS Employer Identification No.)
 2                              30313 (Zip Code)  ,
                                0   1  \
 0                            NaN NaN
 1            Title of each class NaN
 2  COMMON STOCK, $0.25 PAR VALUE NaN

                                            2
 0                                        NaN
 1  Name of each exchange on which registered
 2                    NEW YORK STOCK EXCHANGE  ,
                                                0  \
 0                                            NaN
 1                      Large accelerated filer ý
 2  (Do not check if a smaller reporting company)

                                                1  \
 0                                            NaN
 1                                            NaN
 2  (Do not check if a smaller reporting company)

                                                2  \
 0                                            NaN
 1                            Accelerated filer o
 2  (Do not check if a smaller reporting company)

                                                3  \
 0                                            NaN
 1                                            NaN
 2  (Do not check if a smaller reporting company)

                                                4  \
 0                                            NaN
 1                        Non-accelerated filer o
 2  (Do not check if a smaller reporting company)

                                                5  \
 0                                            NaN
 1                                            NaN
 2  (Do not check if a smaller reporting company)

                                                6
 0                                            NaN
 1                    Smaller reporting company o
 2  (Do not check if a smaller reporting company)  ,
            0   1                                                  2   3     4  \
 0        NaN NaN                                                NaN NaN   NaN
 1        NaN NaN                                                NaN NaN  Page
 2        NaN NaN                         Forward-Looking Statements NaN   NaN
 3     Part I NaN                                                NaN NaN   NaN
 4    Item 1. NaN                                           Business NaN   NaN
 5   Item 1A. NaN                                       Risk Factors NaN   NaN
 6   Item 1B. NaN                          Unresolved Staff Comments NaN   NaN
 7    Item 2. NaN                                         Properties NaN   NaN
 8    Item 3. NaN                                  Legal Proceedings NaN   NaN
 9    Item 4. NaN  Submission of Matters to a Vote of Security Ho... NaN   NaN
 10   Item X. NaN                  Executive Officers of the Company NaN   NaN
 11   Part II NaN                                                NaN NaN   NaN
 12   Item 5. NaN  Market for Registrant's Common Equity, Related... NaN   NaN
 13   Item 6. NaN                            Selected Financial Data NaN   NaN
 14   Item 7. NaN  Management's Discussion and Analysis of Financ... NaN   NaN
 15  Item 7A. NaN  Quantitative and Qualitative Disclosures About... NaN   NaN
 16   Item 8. NaN        Financial Statements and Supplementary Data NaN   NaN
 17   Item 9. NaN  Changes in and Disagreements with Accountants ... NaN   NaN
 18  Item 9A. NaN                            Controls and Procedures NaN   NaN
 19  Item 9B. NaN                                  Other Information NaN   NaN
 20  Part III NaN                                                NaN NaN   NaN
 21  Item 10. NaN  Directors, Executive Officers and Corporate Go... NaN   NaN
 22  Item 11. NaN                             Executive Compensation NaN   NaN
 23  Item 12. NaN  Security Ownership of Certain Beneficial Owner... NaN   NaN
 24  Item 13. NaN  Certain Relationships and Related Transactions... NaN   NaN
 25  Item 14. NaN             Principal Accountant Fees and Services NaN   NaN
 26   Part IV NaN                                                NaN NaN   NaN
 27  Item 15. NaN         Exhibits and Financial Statement Schedules NaN   NaN
 28       NaN NaN                                         Signatures NaN   NaN

        5   6
 0    NaN NaN
 1   Page NaN
 2      1 NaN
 3    NaN NaN
 4      1 NaN
 5     12 NaN
 6     19 NaN
 7     20 NaN
 8     20 NaN
 9     22 NaN
 10    22 NaN
 11   NaN NaN
 12    25 NaN
 13    28 NaN
 14    28 NaN
 15    65 NaN
 16    66 NaN
 17   128 NaN
 18   128 NaN
 19   128 NaN
 20   NaN NaN
 21   128 NaN
 22   129 NaN
 23   129 NaN
 24   129 NaN
 25   129 NaN
 26   NaN NaN
 27   130 NaN
 28   139 NaN  ,
                 0   1                           2   \
 0              NaN NaN                         NaN
 1              NaN NaN  Common Stock Market Prices
 2              NaN NaN                        High
 3             2009 NaN                         NaN
 4   Fourth quarter NaN                         NaN
 5    Third quarter NaN                         NaN
 6   Second quarter NaN                         NaN
 7    First quarter NaN                         NaN
 8             2008 NaN                         NaN
 9   Fourth quarter NaN                         NaN
 10   Third quarter NaN                         NaN
 11  Second quarter NaN                         NaN
 12   First quarter NaN                         NaN

                             3                           4   \
 0                          NaN                         NaN
 1   Common Stock Market Prices  Common Stock Market Prices
 2                         High                         NaN
 3                          NaN                         NaN
 4                      $ 59.45                         NaN
 5                        54.12                         NaN
 6                        49.94                         NaN
 7                        46.00                         NaN
 8                          NaN                         NaN
 9                      $ 55.00                         NaN
 10                       55.84                         NaN
 11                       61.84                         NaN
 12                       65.59                         NaN

                             5                           6   7         8   \
 0                          NaN                         NaN NaN       NaN
 1   Common Stock Market Prices  Common Stock Market Prices NaN       NaN
 2                          Low                         Low NaN  Declared
 3                          NaN                         NaN NaN       NaN
 4                          NaN                     $ 52.71 NaN       NaN
 5                          NaN                       47.42 NaN       NaN
 6                          NaN                       42.00 NaN       NaN
 7                          NaN                       37.44 NaN       NaN
 8                          NaN                         NaN NaN       NaN
 9                          NaN                     $ 40.29 NaN       NaN
 10                         NaN                       49.44 NaN       NaN
 11                         NaN                       51.83 NaN       NaN
 12                         NaN                       56.49 NaN       NaN

            9   10
 0         NaN NaN
 1   Dividends NaN
 2    Declared NaN
 3         NaN NaN
 4      $ 0.41 NaN
 5        0.41 NaN
 6        0.41 NaN
 7        0.41 NaN
 8         NaN NaN
 9      $ 0.38 NaN
 10       0.38 NaN
 11       0.38 NaN
 12       0.38 NaN  ,
                                              0   1  \
 0                                          NaN NaN
 1                                       Period NaN
 2                                          NaN NaN
 3     October 3, 2009 through October 30, 2009 NaN
 4   October 31, 2009 through November 27, 2009 NaN
 5  November 28, 2009 through December 31, 2009 NaN
 6                                          NaN NaN
 7                                        Total NaN
 8                                          NaN NaN

                                   2    3                             4   5  \
 0                               NaN  NaN                           NaN NaN
 1  Total Number of Shares Purchased  1.0  Average Price Paid Per Share NaN
 2                               NaN  NaN                           NaN NaN
 3                            234569  NaN                       $ 54.35 NaN
 4                           5670253  NaN                         56.92 NaN
 5                          16057187  NaN                         58.20 NaN
 6                               NaN  NaN                           NaN NaN
 7                          21962009  NaN                       $ 57.83 NaN
 8                               NaN  NaN                           NaN NaN

                                                    6    7  \
 0                                                NaN  NaN
 1  Total Number of Shares Purchased as Part of Pu...  2.0
 2                                                NaN  NaN
 3                                             200000  NaN
 4                                            5665000  NaN
 5                                           15800000  NaN
 6                                                NaN  NaN
 7                                           21665000  NaN
 8                                                NaN  NaN

                                                    8   9
 0                                                NaN NaN
 1  Maximum Number of Shares That May Yet Be Purch... NaN
 2                                                NaN NaN
 3                                          215810958 NaN
 4                                          210145958 NaN
 5                                          194345958 NaN
 6                                                NaN NaN
 7                                                NaN NaN
 8                                                NaN NaN  ,
                                                    0  \
 0                                                NaN
 1  1 The total number of shares purchased include...
 2  2 On July 20, 2006, we publicly announced that...

                                                    1  \
 0                                                NaN
 1  1 The total number of shares purchased include...
 2  2 On July 20, 2006, we publicly announced that...

                                                    2  \
 0                                                NaN
 1  1 The total number of shares purchased include...
 2  2 On July 20, 2006, we publicly announced that...

                                                    3  \
 0                                                NaN
 1  1 The total number of shares purchased include...
 2  2 On July 20, 2006, we publicly announced that...

                                                    4  \
 0                                                NaN
 1  1 The total number of shares purchased include...
 2  2 On July 20, 2006, we publicly announced that...

                                                    5  \
 0                                                NaN
 1  1 The total number of shares purchased include...
 2  2 On July 20, 2006, we publicly announced that...

                                                    6  \
 0                                                NaN
 1  1 The total number of shares purchased include...
 2  2 On July 20, 2006, we publicly announced that...

                                                    7  \
 0                                                NaN
 1  1 The total number of shares purchased include...
 2  2 On July 20, 2006, we publicly announced that...

                                                    8   9
 0                                                NaN NaN
 1  1 The total number of shares purchased include... NaN
 2  2 On July 20, 2006, we publicly announced that... NaN  ,
                                                    0   \
 0                                                 NaN
 1                             Year Ended December 31,
 2                 (In millions except per share data)
 3                               SUMMARY OF OPERATIONS
 4                              Net operating revenues
 5   Net income attributable to shareowners of The ...
 6                                                 NaN
 7                                      PER SHARE DATA
 8                                    Basic net income
 9                                  Diluted net income
 10                                     Cash dividends
 11                                                NaN
 12                                 BALANCE SHEET DATA
 13                                       Total assets
 14                                     Long-term debt
 15                                                NaN

                                      1                                    2   \
 0                                   NaN                                  NaN
 1                                   NaN                                  NaN
 2   (In millions except per share data)  (In millions except per share data)
 3                                   NaN                                  NaN
 4                                   NaN                                  NaN
 5                                   NaN                                  NaN
 6                                   NaN                                  NaN
 7                                   NaN                                  NaN
 8                                   NaN                                  NaN
 9                                   NaN                                  NaN
 10                                  NaN                                  NaN
 11                                  NaN                                  NaN
 12                                  NaN                                  NaN
 13                                  NaN                                  NaN
 14                                  NaN                                  NaN
 15                                  NaN                                  NaN

                                      3                                    4   \
 0                                   NaN                                  NaN
 1                                  2009                                  NaN
 2   (In millions except per share data)  (In millions except per share data)
 3                                   NaN                                  NaN
 4                              $ 30,990                                  NaN
 5                                  6824                                  NaN
 6                                   NaN                                  NaN
 7                                   NaN                                  NaN
 8                                $ 2.95                                  NaN
 9                                  2.93                                  NaN
 10                                 1.64                                  NaN
 11                                  NaN                                  NaN
 12                                  NaN                                  NaN
 13                             $ 48,671                                  NaN
 14                                 5059                                  NaN
 15                                  NaN                                  NaN

                                      5                                    6   \
 0                                   NaN                                  NaN
 1                                   NaN                                 2008
 2   (In millions except per share data)  (In millions except per share data)
 3                                   NaN                                  NaN
 4                                   NaN                             $ 31,944
 5                                   NaN                                 5807
 6                                   NaN                                  NaN
 7                                   NaN                                  NaN
 8                                   NaN                               $ 2.51
 9                                   NaN                                 2.49
 10                                  NaN                                 1.52
 11                                  NaN                                  NaN
 12                                  NaN                                  NaN
 13                                  NaN                             $ 40,519
 14                                  NaN                                 2781
 15                                  NaN                                  NaN

                                      7                                    8   \
 0                                   NaN                                  NaN
 1                                   NaN                                  NaN
 2   (In millions except per share data)  (In millions except per share data)
 3                                   NaN                                  NaN
 4                                   NaN                                  NaN
 5                                   NaN                                  NaN
 6                                   NaN                                  NaN
 7                                   NaN                                  NaN
 8                                   NaN                                  NaN
 9                                   NaN                                  NaN
 10                                  NaN                                  NaN
 11                                  NaN                                  NaN
 12                                  NaN                                  NaN
 13                                  NaN                                  NaN
 14                                  NaN                                  NaN
 15                                  NaN                                  NaN

                                      9                                    10  \
 0                                   NaN                                  NaN
 1                                  2007                                    1
 2   (In millions except per share data)  (In millions except per share data)

In [5]:
len(dataset)

137

In [6]:
#using index to get your table

financial_report = dataset[8]

In [7]:
financial_report.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Year Ended December 31,",NaN,NaN,2009,NaN,NaN,2008,NaN,NaN,2007,1,NaN,2006,NaN,NaN,2005,2.0
2,(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),NaN
3,SUMMARY OF OPERATIONS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Net operating revenues,NaN,NaN,"$ 30,990",NaN,NaN,"$ 31,944",NaN,NaN,"$ 28,857",NaN,NaN,"$ 24,088",NaN,NaN,"$ 23,104",NaN
5,Net income attributable to shareowners of The ...,NaN,NaN,6824,NaN,NaN,5807,NaN,NaN,5981,NaN,NaN,5080,NaN,NaN,4872,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,PER SHARE DATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Basic net income,NaN,NaN,$ 2.95,NaN,NaN,$ 2.51,NaN,NaN,$ 2.59,NaN,NaN,$ 2.16,NaN,NaN,$ 2.04,NaN
9,Diluted net income,NaN,NaN,2.93,NaN,NaN,2.49,NaN,NaN,2.57,NaN,NaN,2.16,NaN,NaN,2.04,NaN

In [8]:
#selecting the relevant columns
financial_report = dataset[8][[0,3,6,9,12,15]]

In [9]:
financial_report

,0,3,6,9,12,15
0,NaN,NaN,NaN,NaN,NaN,NaN
1,"Year Ended December 31,",2009,2008,2007,2006,2005
2,(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data)
3,SUMMARY OF OPERATIONS,NaN,NaN,NaN,NaN,NaN
4,Net operating revenues,"$ 30,990","$ 31,944","$ 28,857","$ 24,088","$ 23,104"
5,Net income attributable to shareowners of The ...,6824,5807,5981,5080,4872
6,NaN,NaN,NaN,NaN,NaN,NaN
7,PER SHARE DATA,NaN,NaN,NaN,NaN,NaN
8,Basic net income,$ 2.95,$ 2.51,$ 2.59,$ 2.16,$ 2.04
9,Diluted net income,2.93,2.49,2.57,2.16,2.04
10,Cash dividends,1.64,1.52,1.36,1.24,1.12
11,NaN,NaN,NaN,NaN,NaN,NaN
12,BALANCE SHEET DATA,NaN,NaN,NaN,NaN,NaN
13,Total assets,"$ 48,671","$ 40,519","$ 43,269","$ 29,963","$ 29,427"
14,Long-term debt,5059,2781,3277,1314,1154
15,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#removing null values
financial_report = financial_report.dropna()
financial_report

,0,3,6,9,12,15
1,"Year Ended December 31,",2009,2008,2007,2006,2005
2,(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data)
4,Net operating revenues,"$ 30,990","$ 31,944","$ 28,857","$ 24,088","$ 23,104"
5,Net income attributable to shareowners of The ...,6824,5807,5981,5080,4872
8,Basic net income,$ 2.95,$ 2.51,$ 2.59,$ 2.16,$ 2.04
9,Diluted net income,2.93,2.49,2.57,2.16,2.04
10,Cash dividends,1.64,1.52,1.36,1.24,1.12
13,Total assets,"$ 48,671","$ 40,519","$ 43,269","$ 29,963","$ 29,427"
14,Long-term debt,5059,2781,3277,1314,1154

In [11]:
#naming all columns
financial_report.columns = ['31 Dec End of Year', '2009',	'2008',	'2007',	'2006',	'2005']
financial_report

,31 Dec End of Year,2009,2008,2007,2006,2005
1,"Year Ended December 31,",2009,2008,2007,2006,2005
2,(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data),(In millions except per share data)
4,Net operating revenues,"$ 30,990","$ 31,944","$ 28,857","$ 24,088","$ 23,104"
5,Net income attributable to shareowners of The ...,6824,5807,5981,5080,4872
8,Basic net income,$ 2.95,$ 2.51,$ 2.59,$ 2.16,$ 2.04
9,Diluted net income,2.93,2.49,2.57,2.16,2.04
10,Cash dividends,1.64,1.52,1.36,1.24,1.12
13,Total assets,"$ 48,671","$ 40,519","$ 43,269","$ 29,963","$ 29,427"
14,Long-term debt,5059,2781,3277,1314,1154

In [12]:
#remove unneccerassary rows
financial_report =  financial_report.drop(financial_report.index[0])
financial_report =  financial_report.drop(financial_report.index[0])

financial_report

,31 Dec End of Year,2009,2008,2007,2006,2005
4,Net operating revenues,"$ 30,990","$ 31,944","$ 28,857","$ 24,088","$ 23,104"
5,Net income attributable to shareowners of The ...,6824,5807,5981,5080,4872
8,Basic net income,$ 2.95,$ 2.51,$ 2.59,$ 2.16,$ 2.04
9,Diluted net income,2.93,2.49,2.57,2.16,2.04
10,Cash dividends,1.64,1.52,1.36,1.24,1.12
13,Total assets,"$ 48,671","$ 40,519","$ 43,269","$ 29,963","$ 29,427"
14,Long-term debt,5059,2781,3277,1314,1154

In [13]:
#resetting the index
financial_report.reset_index(inplace = True)
financial_report

,index,31 Dec End of Year,2009,2008,2007,2006,2005
0,4,Net operating revenues,"$ 30,990","$ 31,944","$ 28,857","$ 24,088","$ 23,104"
1,5,Net income attributable to shareowners of The ...,6824,5807,5981,5080,4872
2,8,Basic net income,$ 2.95,$ 2.51,$ 2.59,$ 2.16,$ 2.04
3,9,Diluted net income,2.93,2.49,2.57,2.16,2.04
4,10,Cash dividends,1.64,1.52,1.36,1.24,1.12
5,13,Total assets,"$ 48,671","$ 40,519","$ 43,269","$ 29,963","$ 29,427"
6,14,Long-term debt,5059,2781,3277,1314,1154

In [14]:
#drop the index column
financial_report.drop(columns=['index'], inplace = True)

In [15]:
financial_report

,31 Dec End of Year,2009,2008,2007,2006,2005
0,Net operating revenues,"$ 30,990","$ 31,944","$ 28,857","$ 24,088","$ 23,104"
1,Net income attributable to shareowners of The ...,6824,5807,5981,5080,4872
2,Basic net income,$ 2.95,$ 2.51,$ 2.59,$ 2.16,$ 2.04
3,Diluted net income,2.93,2.49,2.57,2.16,2.04
4,Cash dividends,1.64,1.52,1.36,1.24,1.12
5,Total assets,"$ 48,671","$ 40,519","$ 43,269","$ 29,963","$ 29,427"
6,Long-term debt,5059,2781,3277,1314,1154

In [16]:
#defining a function to remove $ and , signs
def replace_func(df, col):
  char_list = ['$ ',',']

  for char in char_list:
      df[col] = df[col].apply(lambda a: str(a).replace(char,''))

In [17]:
col_list = ['2009',	'2008',	'2007',	'2006',	'2005']

for col in col_list:
  replace_func(financial_report,col)

In [18]:
financial_report

,31 Dec End of Year,2009,2008,2007,2006,2005
0,Net operating revenues,30990,31944,28857,24088,23104
1,Net income attributable to shareowners of The ...,6824,5807,5981,5080,4872
2,Basic net income,2.95,2.51,2.59,2.16,2.04
3,Diluted net income,2.93,2.49,2.57,2.16,2.04
4,Cash dividends,1.64,1.52,1.36,1.24,1.12
5,Total assets,48671,40519,43269,29963,29427
6,Long-term debt,5059,2781,3277,1314,1154

In [19]:
#check datatypes
financial_report.dtypes

31 Dec End of Year    object
2009                  object
2008                  object
2007                  object
2006                  object
2005                  object
dtype: object

In [20]:
#convert object to float
financial_report[['2009',	'2008',	'2007',	'2006',	'2005']] = financial_report[['2009',	'2008',	'2007',	'2006',	'2005']].astype(float)

In [22]:
financial_report.dtypes

31 Dec End of Year     object
2009                  float64
2008                  float64
2007                  float64
2006                  float64
2005                  float64
dtype: object

In [23]:
#making a pie chart for year 2009
fig = px.pie(financial_report, values='2009', names='31 Dec End of Year', title = '2009 Yearly financial report')
fig.show()